platform :ios, '8.0'
inhibit_all_warnings!

target 'OKBluetooth_Example' do
  pod 'OKBluetooth', :path => '../'

  target 'OKBluetooth_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
  end
end
